/*
 * GENERATED BY wfof_gen v2.0 on 6.4.2016 14:06:28
 *
 * Created by Martin Winkelhofer 02,03/2016
 * W-Dimension / wdim / wdim0 / winkelhofer.m@gmail.com / https://github.com/wdim0
 *    _____ __          ____         ______         __
 *   / __(_) /__ ___   / __ \___    / __/ /__ ____ / /
 *  / _// / / -_|_-<  / /_/ / _ \  / _// / _ `(_-</ _ \
 * /_/ /_/_/\__/___/  \____/_//_/ /_/ /_/\_,_/___/_//_/
 *
 * This file is part of WFOF - W-Dimension's Files On Flash (for ESP8266).
 *
 * WFOF is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * WFOF is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WFOF. If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef __WFOF_IDXS_H__
#define __WFOF_IDXS_H__

#define WFOF_FILES_CNT		13

#define WFOF_ALIGN_BYTES		4

#define WFOF_IDX_BG_PNG		0
#define WFOF_IDX_FAVICON_PNG		1
#define WFOF_IDX_FLASH_CONTENT_BIN		2
#define WFOF_IDX_FLASH_INFO_HTML		3
#define WFOF_IDX_FOTA_HTML		4
#define WFOF_IDX_FOTA_RESULT_HTML		5
#define WFOF_IDX_INDEX_HTML		6
#define WFOF_IDX_LARGER_IMAGE_JPG		7
#define WFOF_IDX_MD5_JS		8
#define WFOF_IDX_SET_GPIO2_HTML		9
#define WFOF_IDX_STYLE_CSS		10
#define WFOF_IDX___WHTTPD_ERR_RESP_HTML		11
#define WFOF_IDX___WHTTPD_HEADER_TXT		12

#define WFOF_SIZE_BG_PNG		10242
#define WFOF_SIZE_FAVICON_PNG		287
#define WFOF_SIZE_FLASH_CONTENT_BIN		18
#define WFOF_SIZE_FLASH_INFO_HTML		496
#define WFOF_SIZE_FOTA_HTML		1116
#define WFOF_SIZE_FOTA_RESULT_HTML		425
#define WFOF_SIZE_INDEX_HTML		532
#define WFOF_SIZE_LARGER_IMAGE_JPG		113227
#define WFOF_SIZE_MD5_JS		4595
#define WFOF_SIZE_SET_GPIO2_HTML		641
#define WFOF_SIZE_STYLE_CSS		562
#define WFOF_SIZE___WHTTPD_ERR_RESP_HTML		353
#define WFOF_SIZE___WHTTPD_HEADER_TXT		78

#endif
